// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBXGLAixvQcBgdXY-15Evsk3Lk7pDdpE',
    appId: '1:719921874155:web:810aa03fdab14b555d2aae',
    messagingSenderId: '719921874155',
    projectId: 'crudflutter-a3743',
    authDomain: 'crudflutter-a3743.firebaseapp.com',
    storageBucket: 'crudflutter-a3743.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGPfqWdQt7oECZ8YXVJ07X5mYPp-F4occ',
    appId: '1:719921874155:android:bbd42e7259e760615d2aae',
    messagingSenderId: '719921874155',
    projectId: 'crudflutter-a3743',
    storageBucket: 'crudflutter-a3743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAae-HTfbd5o4CgnFDSFH7jx3c9Yh-rf0M',
    appId: '1:719921874155:ios:3fa9178fdbce8e0c5d2aae',
    messagingSenderId: '719921874155',
    projectId: 'crudflutter-a3743',
    storageBucket: 'crudflutter-a3743.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAae-HTfbd5o4CgnFDSFH7jx3c9Yh-rf0M',
    appId: '1:719921874155:ios:3fa9178fdbce8e0c5d2aae',
    messagingSenderId: '719921874155',
    projectId: 'crudflutter-a3743',
    storageBucket: 'crudflutter-a3743.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfBXGLAixvQcBgdXY-15Evsk3Lk7pDdpE',
    appId: '1:719921874155:web:97c9f85593ad28a95d2aae',
    messagingSenderId: '719921874155',
    projectId: 'crudflutter-a3743',
    authDomain: 'crudflutter-a3743.firebaseapp.com',
    storageBucket: 'crudflutter-a3743.firebasestorage.app',
  );
}
